# Generated by Django 2.1.5 on 2019-06-02 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Evento')),
                ('cupos', models.SmallIntegerField(verbose_name='Cupos disponibles')),
                ('fecha', models.DateTimeField(verbose_name='Fecha evento')),
                ('ubicacion', models.CharField(max_length=200, verbose_name='Dirección evento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='eventos', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ult. actualizacion')),
                ('club_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clubes.Club', verbose_name='Codigo de club')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha'],
            },
        ),
    ]
