# Generated by Django 2.1.5 on 2019-06-26 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_asistentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistentes',
            name='miembro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.Miembro', verbose_name='Miembro asitente'),
        ),
    ]
