# Generated by Django 2.1.5 on 2019-04-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_org', models.CharField(max_length=11, verbose_name='Rut organizacion')),
                ('nombre_org', models.CharField(max_length=200, verbose_name='Nombre organizacion')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion club')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Telefono de contacto')),
                ('correo_contacto', models.CharField(max_length=200, verbose_name='Email de contacto')),
                ('cant_max_miembros', models.SmallIntegerField(verbose_name='Cantidad maxima de miembros')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ult. actualizacion')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['-created'],
            },
        ),
    ]
