# Generated by Django 2.1.5 on 2019-06-22 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario del club'),
        ),
    ]
