# Generated by Django 2.1.5 on 2019-06-26 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0002_club_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario del club'),
        ),
    ]
