# Generated by Django 2.1.5 on 2019-07-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubes', '0003_auto_20190626_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cantidad_miembros',
            field=models.SmallIntegerField(default=0, verbose_name='Cantidad actual de miembros'),
        ),
    ]
