# Generated by Django 2.1.5 on 2019-04-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres')),
                ('apellido_p', models.CharField(max_length=20, verbose_name='Apellido paterno')),
                ('apellido_m', models.CharField(max_length=20, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo electronico')),
                ('celular', models.CharField(max_length=12, verbose_name='Numero celular')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('sexo', models.CharField(max_length=1, verbose_name='Genero')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ult. actualizacion')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubes.Club', verbose_name='Club')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'ordering': ['apellido_p'],
            },
        ),
    ]
