# Generated by Django 2.1.5 on 2019-06-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='genero',
            field=models.CharField(max_length=15, verbose_name='Genero'),
        ),
    ]
