# Generated by Django 2.2 on 2019-04-29 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_auto_20190428_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='club',
            new_name='club_id',
        ),
    ]
