# Generated by Django 2.1.5 on 2019-06-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_auto_20190617_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='dosis_diaria',
            field=models.SmallIntegerField(default=0, verbose_name='Dosis diaria recetada'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='fecha_expiracion_receta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de expiración de receta'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='fotocopia_carnet_a',
            field=models.ImageField(blank=True, null=True, upload_to='miembros', verbose_name='Fotocopia de carnet A'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='fotocopia_carnet_b',
            field=models.ImageField(blank=True, null=True, upload_to='miembros', verbose_name='Fotocopia de carnet B'),
        ),
        migrations.AddField(
            model_name='miembro',
            name='receta',
            field=models.ImageField(blank=True, null=True, upload_to='miembros', verbose_name='Receta'),
        ),
    ]
