# Generated by Django 2.1.5 on 2019-05-30 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_auto_20190428_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='sexo',
            new_name='genero',
        ),
    ]
