# Generated by Django 2.1.5 on 2019-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_auto_20190619_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='fotocopia_carnet_a',
            field=models.FileField(blank=True, null=True, upload_to='miembros', verbose_name='Fotocopia de carnet A'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='fotocopia_carnet_b',
            field=models.FileField(blank=True, null=True, upload_to='miembros', verbose_name='Fotocopia de carnet B'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='receta',
            field=models.FileField(blank=True, null=True, upload_to='miembros', verbose_name='Receta'),
        ),
    ]
