# Generated by Django 2.1.5 on 2019-09-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido_m',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='profile',
            name='apellido_p',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellido paterno'),
        ),
        migrations.AddField(
            model_name='profile',
            name='correo',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombres',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Primer nombre'),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero_cel',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.Tipo_Cuenta'),
        ),
    ]
