# Generated by Django 2.1.5 on 2019-09-19 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.ForeignKey(default=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de usuario'),
        ),
    ]
