# Generated by Django 2.1.5 on 2019-06-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_auto_20190617_1523'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reservar', models.SmallIntegerField(verbose_name='Cantidad a reservar')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de ult. actualizacion')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.Miembro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Producto')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['created', 'updated'],
            },
        ),
    ]
