# Generated by Django 2.1.5 on 2019-06-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='P', max_length=1, verbose_name='Estado'),
        ),
    ]
