# Generated by Django 2.1.5 on 2019-06-17 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20190617_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='miembro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miembros.Miembro'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
