# Generated by Django 2.1.5 on 2019-06-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_precio_gramo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.IntegerField(default=0, verbose_name='Monto total de la reserva'),
        ),
    ]
