# Generated by Django 2.1.5 on 2019-06-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_reserva_precio_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-created'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
