# Generated by Django 2.1.5 on 2019-11-05 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0002_paciente_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario_disponible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha consulta')),
                ('hora_inicio', models.TimeField(verbose_name='Hora inicio de consulta')),
                ('hora_termino', models.TimeField(verbose_name='Hora termino de consulta')),
                ('duracion', models.IntegerField(verbose_name='Duracion de la consulta')),
                ('estado', models.BooleanField(verbose_name='Estado')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Medico')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_reservado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva consulta')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.Horario_disponible', verbose_name='Horario seleccionado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Paciente', verbose_name='Paciente')),
            ],
        ),
    ]
